"""TypedDict agent state schema for the multi-agent LangGraph coordinator."""
from __future__ import annotations

from typing import Annotated, Any, Optional
from typing_extensions import TypedDict
import operator


class AgentState(TypedDict):
    """Shared state passed between all nodes in the LangGraph.

    Attributes:
        user_input: Original user request.
        plan: Ordered list of subtasks generated by the Planner.
        current_task: Index of the task currently being executed.
        tool_results: Accumulated results from tool calls.
        messages: Full conversation history (appended via operator.add).
        reviewer_score: 0.0–1.0 score from the Reviewer node.
        retry_count: Number of times the current task has been retried.
        final_output: Assembled final response to return to the user.
        error: Optional error message if a node fails.
    """

    user_input: str
    plan: list[str]
    current_task: int
    tool_results: Annotated[list[dict[str, Any]], operator.add]
    messages: Annotated[list[Any], operator.add]
    reviewer_score: float
    retry_count: int
    final_output: Optional[str]
    error: Optional[str]
